### ISSUE TITLE
Where is 110m-admin-0-countries.zip?

### ISSUE THREAD

**Issue by bostontrader** [akx/docker-mapnik#2]
Hey akx,
Sorry to keep pestering you. In the Dockerfile, at line 31 of commit t bcfdbb1, we see COPY 110m-admin-0-countries.zip ... but alas, said file is nowhere to be found.  I'm sure I could fix this, so if you'd like a change request, I'd be happy to discuss further how to that.

**Comment by akx** [comment]
Sorry! I've no idea why that file was missing. It's (re?)added now...
